# Generated by Django 6.0.6 on 2026-07-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bororwing',
            new_name='Borrowing',
        ),
    ]
